import { Router, Response } from 'express';
import bcrypt from 'bcryptjs';
import { pool } from '../config/database';
import { authMiddleware, requireRole, AuthRequest } from '../middleware/auth';

const router = Router();

/** Quita tildes/diacriticos y deja solo [a-z0-9]. */
function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

/**
 * Genera el username base a partir del nombre completo, siguiendo la
 * convencion existente: inicial del primer nombre + primer apellido.
 * Ej: "Eduardo Jose Noriega Campos" -> "enoriega"
 * Con 4+ palabras se asume [nombre nombre apPaterno apMaterno]; con menos,
 * el apellido es la segunda palabra.
 */
export function buildUsernameBase(fullName: string): string {
  const parts = (fullName || '').trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return 'usuario';

  if (parts.length === 1) return slugify(parts[0]!) || 'usuario';

  const surnameIdx = parts.length >= 4 ? 2 : 1;
  const initial = slugify(parts[0]!).charAt(0);
  const surname = slugify(parts[surnameIdx]!);
  const base = `${initial}${surname}`;

  return base || slugify(parts.join('')) || 'usuario';
}

/**
 * "Sin DNI" siempre se guarda como NULL: Postgres admite multiples NULL en un
 * UNIQUE, pero solo una cadena vacia (dos usuarios sin DNI chocarian).
 */
function normalizeDni(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed === '' ? null : trimmed;
}

/** Traduce una violacion de unicidad al mensaje que ve el usuario. */
function conflictMessage(err: any): string | null {
  if (err?.code !== '23505') return null;
  if (err.constraint === 'users_dni_key') return 'Ya existe un usuario registrado con ese DNI';
  if (err.constraint === 'users_username_key') return 'El nombre de usuario ya existe';
  return 'Ya existe un registro con esos datos';
}

/** Devuelve un username libre, agregando sufijo numerico si hace falta. */
async function findFreeUsername(base: string): Promise<string> {
  for (let n = 1; n <= 99; n++) {
    const candidate = n === 1 ? base : `${base}${n}`;
    const exists = await pool.query('SELECT 1 FROM users WHERE username = $1', [candidate]);
    if (exists.rows.length === 0) return candidate;
  }
  return `${base}${Date.now().toString().slice(-5)}`;
}

router.use(authMiddleware);

router.get('/', requireRole('admin', 'superadmin'), async (_req: AuthRequest, res: Response): Promise<void> => {
  try {
    const result = await pool.query(
      'SELECT id, username, full_name, dni, email, role, active, created_at FROM users ORDER BY created_at DESC'
    );
    res.json(result.rows);
  } catch (err) {
    console.error('Error al listar usuarios:', err);
    res.status(500).json({ message: 'Error al obtener usuarios' });
  }
});

router.post('/', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const { username, password, full_name, dni, email, role } = req.body;

  if (!full_name) {
    res.status(400).json({ message: 'El nombre completo es requerido' });
    return;
  }

  const providedUsername = slugify(username || '');
  const assignedRole = role || 'user';
  if (assignedRole === 'superadmin' && req.user!.role !== 'superadmin') {
    res.status(403).json({ message: 'Solo un superadmin puede crear superadmins' });
    return;
  }
  if (assignedRole === 'admin' && req.user!.role !== 'superadmin') {
    res.status(403).json({ message: 'Solo un superadmin puede crear admins' });
    return;
  }

  try {
    // Si el admin no escribio un username, se autogenera desde el nombre completo
    // y se resuelven los duplicados con sufijo numerico.
    const autoGenerated = providedUsername === '';
    const explicitPassword = typeof password === 'string' && password.length > 0;

    // La contrasena inicial es el propio username, salvo que se envie una.
    // Se resuelve por username final para que coincida incluso con sufijo (rquispe2).
    const insert = async (name: string) => {
      const hash = await bcrypt.hash(explicitPassword ? password : name, 12);
      return pool.query(
        `INSERT INTO users (username, password_hash, full_name, dni, email, role)
         VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING id, username, full_name, dni, email, role, active, created_at`,
        [name, hash, full_name, normalizeDni(dni), email || null, assignedRole]
      );
    };

    const finalUsername = autoGenerated
      ? await findFreeUsername(buildUsernameBase(full_name))
      : providedUsername;

    try {
      const result = await insert(finalUsername);
      res.status(201).json(result.rows[0]);
    } catch (err: any) {
      // Carrera: otro registro tomo el username entre la consulta y el insert.
      // Solo reintentamos por el username; un DNI repetido debe informarse.
      if (err.code === '23505' && err.constraint === 'users_username_key' && autoGenerated) {
        const retry = await insert(await findFreeUsername(buildUsernameBase(full_name)));
        res.status(201).json(retry.rows[0]);
        return;
      }
      throw err;
    }
  } catch (err: any) {
    const conflict = conflictMessage(err);
    if (conflict) {
      res.status(409).json({ message: conflict });
      return;
    }
    console.error('Error al crear usuario:', err);
    res.status(500).json({ message: 'Error al crear usuario' });
  }
});

router.put('/:id', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const id = req.params.id as string;
  const { full_name, dni, email, role, active, password } = req.body;
  const isSuperadmin = req.user!.role === 'superadmin';
  const isSelf = parseInt(id) === req.user!.userId;

  try {
    const target = await pool.query('SELECT role FROM users WHERE id = $1', [id]);
    if (target.rows.length === 0) {
      res.status(404).json({ message: 'Usuario no encontrado' });
      return;
    }
    const targetRole = target.rows[0].role;

    // Los administradores solo pueden gestionar usuarios regulares (o editar su propia info)
    if (!isSuperadmin && !isSelf && targetRole !== 'user') {
      res.status(403).json({ message: 'Los administradores solo pueden gestionar usuarios regulares' });
      return;
    }

    const fields: string[] = [];
    const values: any[] = [];
    let idx = 1;

    if (full_name !== undefined) { fields.push(`full_name = $${idx++}`); values.push(full_name); }
    if (dni !== undefined) { fields.push(`dni = $${idx++}`); values.push(normalizeDni(dni)); }
    if (email !== undefined) { fields.push(`email = $${idx++}`); values.push(email); }

    if (role !== undefined) {
      if (!isSuperadmin) { res.status(403).json({ message: 'Solo superadmins pueden cambiar roles' }); return; }
      fields.push(`role = $${idx++}`); values.push(role);
    }
    if (active !== undefined) {
      if (!isSuperadmin && isSelf) { res.status(403).json({ message: 'No puedes cambiar tu propio estado' }); return; }
      fields.push(`active = $${idx++}`); values.push(active);
    }
    if (password) {
      // Superadmin cambia la contrasena de cualquiera; el admin solo la de usuarios regulares.
      if (!isSuperadmin && targetRole !== 'user') {
        res.status(403).json({ message: 'Los administradores solo pueden cambiar contrasenas de usuarios' });
        return;
      }
      const hash = await bcrypt.hash(password, 12);
      fields.push(`password_hash = $${idx++}`);
      values.push(hash);
    }

    if (fields.length === 0) {
      res.status(400).json({ message: 'Nada que actualizar' });
      return;
    }

    fields.push(`updated_at = CURRENT_TIMESTAMP`);
    values.push(id);

    const result = await pool.query(
      `UPDATE users SET ${fields.join(', ')} WHERE id = $${idx}
       RETURNING id, username, full_name, dni, email, role, active`,
      values
    );

    res.json(result.rows[0]);
  } catch (err: any) {
    const conflict = conflictMessage(err);
    if (conflict) {
      res.status(409).json({ message: conflict });
      return;
    }
    console.error('Error al actualizar usuario:', err);
    res.status(500).json({ message: 'Error al actualizar usuario' });
  }
});

router.delete('/:id', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const id = req.params.id as string;
  const isSuperadmin = req.user!.role === 'superadmin';

  if (parseInt(id) === req.user!.userId) {
    res.status(400).json({ message: 'No puedes eliminarte a ti mismo' });
    return;
  }

  try {
    const target = await pool.query('SELECT role FROM users WHERE id = $1', [id]);
    if (target.rows.length === 0) {
      res.status(404).json({ message: 'Usuario no encontrado' });
      return;
    }

    // Solo un superadmin puede eliminar administradores u otros superadmins
    if (!isSuperadmin && target.rows[0].role !== 'user') {
      res.status(403).json({ message: 'Solo un superadmin puede eliminar administradores' });
      return;
    }

    await pool.query('DELETE FROM users WHERE id = $1', [id]);
    res.json({ message: 'Usuario eliminado' });
  } catch (err) {
    console.error('Error al eliminar usuario:', err);
    res.status(500).json({ message: 'Error al eliminar usuario' });
  }
});

export default router;
