import { Router, Response } from 'express';
import bcrypt from 'bcryptjs';
import type { PoolClient } from 'pg';
import { pool } from '../config/database';
import { authMiddleware, requireRole, AuthRequest } from '../middleware/auth';
import { generateVerificationCode } from '../services/verification';
import { sendInvitation, mailerConfigured } from '../services/mailer';

const router = Router();

/** Quita tildes/diacriticos y deja solo [a-z0-9]. */
function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

/**
 * Genera el username base a partir del nombre completo, siguiendo la
 * convencion existente: inicial del primer nombre + primer apellido.
 * Ej: "Eduardo Jose Noriega Campos" -> "enoriega"
 * Con 4+ palabras se asume [nombre nombre apPaterno apMaterno]; con menos,
 * el apellido es la segunda palabra.
 */
export function buildUsernameBase(fullName: string): string {
  const parts = (fullName || '').trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return 'usuario';

  if (parts.length === 1) return slugify(parts[0]!) || 'usuario';

  const surnameIdx = parts.length >= 4 ? 2 : 1;
  const initial = slugify(parts[0]!).charAt(0);
  const surname = slugify(parts[surnameIdx]!);
  const base = `${initial}${surname}`;

  return base || slugify(parts.join('')) || 'usuario';
}

/**
 * "Sin DNI" siempre se guarda como NULL: Postgres admite multiples NULL en un
 * UNIQUE, pero solo una cadena vacia (dos usuarios sin DNI chocarian).
 */
function normalizeDni(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed === '' ? null : trimmed;
}

/** Traduce una violacion de unicidad al mensaje que ve el usuario. */
function conflictMessage(err: any): string | null {
  if (err?.code !== '23505') return null;
  if (err.constraint === 'users_dni_key') return 'Ya existe un usuario registrado con ese DNI';
  if (err.constraint === 'users_username_key') return 'El nombre de usuario ya existe';
  return 'Ya existe un registro con esos datos';
}

type Queryable = Pick<PoolClient, 'query'>;

/**
 * Devuelve un username libre, agregando sufijo numerico si hace falta.
 * Acepta un client para que, dentro de una transaccion, vea los usuarios
 * insertados en el mismo lote y no repita nombres.
 */
async function findFreeUsername(base: string, db: Queryable = pool): Promise<string> {
  for (let n = 1; n <= 99; n++) {
    const candidate = n === 1 ? base : `${base}${n}`;
    const exists = await db.query('SELECT 1 FROM users WHERE username = $1', [candidate]);
    if (exists.rows.length === 0) return candidate;
  }
  return `${base}${Date.now().toString().slice(-5)}`;
}

/** Codigo de verificacion unico, dentro de la misma transaccion. */
async function findFreeCode(db: Queryable): Promise<string> {
  for (let i = 0; i < 12; i++) {
    const code = generateVerificationCode();
    const exists = await db.query('SELECT 1 FROM certificates WHERE verification_code = $1', [code]);
    if (exists.rows.length === 0) return code;
  }
  throw new Error('No se pudo generar un codigo de verificacion unico');
}

router.use(authMiddleware);

router.get('/', requireRole('admin', 'superadmin'), async (_req: AuthRequest, res: Response): Promise<void> => {
  try {
    const result = await pool.query(
      `SELECT id, username, full_name, dni, email, role, active,
              has_logged_in, first_login_at, invited_at, created_at
       FROM users ORDER BY created_at DESC`
    );
    res.json(result.rows);
  } catch (err) {
    console.error('Error al listar usuarios:', err);
    res.status(500).json({ message: 'Error al obtener usuarios' });
  }
});

router.post('/', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const { username, password, full_name, dni, email, role } = req.body;

  if (!full_name) {
    res.status(400).json({ message: 'El nombre completo es requerido' });
    return;
  }

  const providedUsername = slugify(username || '');
  const assignedRole = role || 'user';
  if (assignedRole === 'superadmin' && req.user!.role !== 'superadmin') {
    res.status(403).json({ message: 'Solo un superadmin puede crear superadmins' });
    return;
  }
  if (assignedRole === 'admin' && req.user!.role !== 'superadmin') {
    res.status(403).json({ message: 'Solo un superadmin puede crear admins' });
    return;
  }

  try {
    // Si el admin no escribio un username, se autogenera desde el nombre completo
    // y se resuelven los duplicados con sufijo numerico.
    const autoGenerated = providedUsername === '';
    const explicitPassword = typeof password === 'string' && password.length > 0;

    // La contrasena inicial es el propio username, salvo que se envie una.
    // Se resuelve por username final para que coincida incluso con sufijo (rquispe2).
    const insert = async (name: string) => {
      const hash = await bcrypt.hash(explicitPassword ? password : name, 12);
      return pool.query(
        `INSERT INTO users (username, password_hash, full_name, dni, email, role)
         VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING id, username, full_name, dni, email, role, active, created_at`,
        [name, hash, full_name, normalizeDni(dni), email || null, assignedRole]
      );
    };

    const finalUsername = autoGenerated
      ? await findFreeUsername(buildUsernameBase(full_name))
      : providedUsername;

    try {
      const result = await insert(finalUsername);
      res.status(201).json(result.rows[0]);
    } catch (err: any) {
      // Carrera: otro registro tomo el username entre la consulta y el insert.
      // Solo reintentamos por el username; un DNI repetido debe informarse.
      if (err.code === '23505' && err.constraint === 'users_username_key' && autoGenerated) {
        const retry = await insert(await findFreeUsername(buildUsernameBase(full_name)));
        res.status(201).json(retry.rows[0]);
        return;
      }
      throw err;
    }
  } catch (err: any) {
    const conflict = conflictMessage(err);
    if (conflict) {
      res.status(409).json({ message: conflict });
      return;
    }
    console.error('Error al crear usuario:', err);
    res.status(500).json({ message: 'Error al crear usuario' });
  }
});

/**
 * Importacion masiva de participantes desde una lista pegada.
 * Crea los usuarios que faltan (reutiliza los que ya existen segun DNI) y,
 * si se indica un curso, emite el certificado de cada uno.
 * Todo ocurre en una transaccion: o entra el lote completo, o no entra nada.
 */
router.post('/import', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const { participants, course_id, type, issue_date } = req.body;

  if (!Array.isArray(participants) || participants.length === 0) {
    res.status(400).json({ message: 'Se requiere al menos un participante' });
    return;
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    let curso: { id: number; hours: number; name: string } | null = null;
    if (course_id) {
      const c = await client.query('SELECT id, hours, name FROM courses WHERE id = $1', [course_id]);
      if (c.rows.length === 0) {
        await client.query('ROLLBACK');
        res.status(404).json({ message: 'Curso no encontrado' });
        return;
      }
      curso = c.rows[0];
    }

    const creados: any[] = [];
    const reutilizados: any[] = [];
    const ignorados: any[] = [];
    const idsParaCertificar: number[] = [];

    for (const p of participants) {
      const fullName = String(p?.full_name ?? '').trim().replace(/\s+/g, ' ');
      if (!fullName) {
        ignorados.push({ motivo: 'Sin nombre', fila: p });
        continue;
      }
      const dni = normalizeDni(typeof p?.dni === 'string' ? p.dni : p?.dni != null ? String(p.dni) : '');

      // Un DNI ya registrado identifica a la persona: se reutiliza su cuenta.
      let userId: number | null = null;
      if (dni) {
        const found = await client.query(
          'SELECT id, username, full_name, dni FROM users WHERE dni = $1', [dni]
        );
        if (found.rows.length > 0) {
          userId = found.rows[0].id;
          reutilizados.push(found.rows[0]);
        }
      }

      if (userId === null) {
        const username = await findFreeUsername(buildUsernameBase(fullName), client);
        const hash = await bcrypt.hash(username, 12); // contrasena inicial = usuario
        const ins = await client.query(
          `INSERT INTO users (username, password_hash, full_name, dni, role)
           VALUES ($1, $2, $3, $4, 'user')
           RETURNING id, username, full_name, dni`,
          [username, hash, fullName, dni]
        );
        userId = ins.rows[0].id;
        creados.push(ins.rows[0]);
      }

      idsParaCertificar.push(userId!);
    }

    let emitidos = 0;
    let yaTenian = 0;
    const certificados: any[] = [];

    if (curso) {
      for (const uid of idsParaCertificar) {
        const dup = await client.query(
          'SELECT 1 FROM certificates WHERE user_id = $1 AND course_id = $2', [uid, curso.id]
        );
        if (dup.rows.length > 0) { yaTenian++; continue; }

        const code = await findFreeCode(client);
        const cert = await client.query(
          `INSERT INTO certificates (user_id, course_id, type, verification_code, issue_date, hours, issued_by)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           RETURNING id, user_id, verification_code`,
          [uid, curso.id, type || 'certificado', code,
           issue_date || new Date().toISOString().split('T')[0], curso.hours, req.user!.userId]
        );
        certificados.push(cert.rows[0]);
        emitidos++;
      }
    }

    await client.query('COMMIT');
    res.status(201).json({
      curso: curso ? { id: curso.id, name: curso.name } : null,
      usuarios: { creados: creados.length, reutilizados: reutilizados.length, ignorados: ignorados.length },
      certificados: { emitidos, ya_tenian: yaTenian },
      detalle: { creados, reutilizados, ignorados, certificados },
    });
  } catch (err: any) {
    await client.query('ROLLBACK');
    const conflict = conflictMessage(err);
    if (conflict) {
      res.status(409).json({ message: `${conflict}. No se importo ningun registro.` });
      return;
    }
    console.error('Error en importacion masiva:', err);
    res.status(500).json({ message: 'Error al importar participantes' });
  } finally {
    client.release();
  }
});

interface InvitableUser { id: number; username: string; full_name: string; email: string | null; role: string; }

/** Envia la invitacion a cada usuario del lote y devuelve el desglose. */
async function enviarInvitacionesLote(
  rows: InvitableUser[], resetPassword: boolean, isSuperadmin: boolean
): Promise<{ enviados: any[]; sinCorreo: any[]; fallidos: any[] }> {
  const enviados: any[] = [];
  const sinCorreo: any[] = [];
  const fallidos: any[] = [];

  for (const u of rows) {
    // Un admin solo invita a usuarios regulares.
    if (!isSuperadmin && u.role !== 'user') {
      fallidos.push({ id: u.id, full_name: u.full_name, motivo: 'Sin permiso sobre este usuario' });
      continue;
    }
    if (!u.email || !u.email.trim()) {
      sinCorreo.push({ id: u.id, full_name: u.full_name });
      continue;
    }
    try {
      // La contrasena a comunicar es el username (valor inicial por defecto).
      if (resetPassword) {
        const hash = await bcrypt.hash(u.username, 12);
        await pool.query('UPDATE users SET password_hash = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2', [hash, u.id]);
      }
      await sendInvitation({
        fullName: u.full_name,
        username: u.username,
        password: u.username,
        email: u.email.trim(),
      });
      await pool.query('UPDATE users SET invited_at = CURRENT_TIMESTAMP WHERE id = $1', [u.id]);
      enviados.push({ id: u.id, full_name: u.full_name, email: u.email });
    } catch (e: any) {
      fallidos.push({ id: u.id, full_name: u.full_name, motivo: e?.message || 'Error al enviar' });
    }
  }
  return { enviados, sinCorreo, fallidos };
}

/**
 * Envia por correo la invitacion de acceso (usuario + contrasena inicial) a un
 * bloque de usuarios elegido manualmente.
 */
router.post('/send-invitations', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const { user_ids, reset_password } = req.body;

  if (!Array.isArray(user_ids) || user_ids.length === 0) {
    res.status(400).json({ message: 'Se requiere al menos un usuario' });
    return;
  }
  if (!mailerConfigured()) {
    res.status(503).json({ message: 'El envio de correos no esta configurado (falta RESEND_API_KEY)' });
    return;
  }

  try {
    const { rows } = await pool.query(
      `SELECT id, username, full_name, email, role FROM users WHERE id = ANY($1::int[])`,
      [user_ids]
    );
    const r = await enviarInvitacionesLote(rows, Boolean(reset_password), req.user!.role === 'superadmin');
    res.json({ enviados: r.enviados.length, sin_correo: r.sinCorreo.length, fallidos: r.fallidos.length, detalle: r });
  } catch (err) {
    console.error('Error al enviar invitaciones:', err);
    res.status(500).json({ message: 'Error al enviar invitaciones' });
  }
});

/**
 * Estado de campana por curso: cuantos participantes ingresaron y cuantos
 * siguen pendientes (nunca ingresaron), para decidir a quien reenviar.
 */
router.get('/campaign-stats', requireRole('admin', 'superadmin'), async (_req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { rows } = await pool.query(
      `SELECT co.id, co.name,
              count(DISTINCT u.id) AS total,
              count(DISTINCT u.id) FILTER (WHERE u.has_logged_in) AS ingresaron,
              count(DISTINCT c.id) FILTER (WHERE c.download_count > 0) AS descargaron,
              count(DISTINCT u.id) FILTER (WHERE NOT u.has_logged_in
                    AND u.email IS NOT NULL AND btrim(u.email) <> '') AS pendientes_con_correo,
              count(DISTINCT u.id) FILTER (WHERE NOT u.has_logged_in
                    AND (u.email IS NULL OR btrim(u.email) = '')) AS pendientes_sin_correo
       FROM courses co
       JOIN certificates c ON c.course_id = co.id
       JOIN users u ON u.id = c.user_id AND u.role = 'user'
       GROUP BY co.id, co.name
       ORDER BY co.name`
    );
    res.json(rows.map((r) => ({
      course_id: r.id,
      course_name: r.name,
      total: Number(r.total),
      ingresaron: Number(r.ingresaron),
      descargaron: Number(r.descargaron),
      pendientes_con_correo: Number(r.pendientes_con_correo),
      pendientes_sin_correo: Number(r.pendientes_sin_correo),
    })));
  } catch (err) {
    console.error('Error en campaign-stats:', err);
    res.status(500).json({ message: 'Error al obtener el estado de las campanas' });
  }
});

/**
 * Campana por curso: envia la invitacion a los participantes de ese curso que
 * NUNCA ingresaron y tienen correo. Es el reenvio dirigido de la campana.
 */
router.post('/send-campaign', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const { course_id, reset_password } = req.body;

  if (!course_id) {
    res.status(400).json({ message: 'Se requiere el curso' });
    return;
  }
  if (!mailerConfigured()) {
    res.status(503).json({ message: 'El envio de correos no esta configurado (falta RESEND_API_KEY)' });
    return;
  }

  try {
    const { rows } = await pool.query(
      `SELECT DISTINCT u.id, u.username, u.full_name, u.email, u.role
       FROM certificates c
       JOIN users u ON u.id = c.user_id
       WHERE c.course_id = $1
         AND u.role = 'user'
         AND NOT u.has_logged_in
         AND u.email IS NOT NULL AND btrim(u.email) <> ''`,
      [course_id]
    );

    if (rows.length === 0) {
      res.json({ enviados: 0, sin_correo: 0, fallidos: 0, mensaje: 'No hay participantes pendientes con correo en este curso' });
      return;
    }

    const r = await enviarInvitacionesLote(rows, Boolean(reset_password), req.user!.role === 'superadmin');
    res.json({ enviados: r.enviados.length, sin_correo: r.sinCorreo.length, fallidos: r.fallidos.length, detalle: r });
  } catch (err) {
    console.error('Error en send-campaign:', err);
    res.status(500).json({ message: 'Error al enviar la campana' });
  }
});

router.put('/:id', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const id = req.params.id as string;
  const { full_name, dni, email, role, active, password } = req.body;
  const isSuperadmin = req.user!.role === 'superadmin';
  const isSelf = parseInt(id) === req.user!.userId;

  try {
    const target = await pool.query('SELECT role FROM users WHERE id = $1', [id]);
    if (target.rows.length === 0) {
      res.status(404).json({ message: 'Usuario no encontrado' });
      return;
    }
    const targetRole = target.rows[0].role;

    // Los administradores solo pueden gestionar usuarios regulares (o editar su propia info)
    if (!isSuperadmin && !isSelf && targetRole !== 'user') {
      res.status(403).json({ message: 'Los administradores solo pueden gestionar usuarios regulares' });
      return;
    }

    const fields: string[] = [];
    const values: any[] = [];
    let idx = 1;

    if (full_name !== undefined) { fields.push(`full_name = $${idx++}`); values.push(full_name); }
    if (dni !== undefined) { fields.push(`dni = $${idx++}`); values.push(normalizeDni(dni)); }
    if (email !== undefined) { fields.push(`email = $${idx++}`); values.push(email); }

    if (role !== undefined) {
      if (!isSuperadmin) { res.status(403).json({ message: 'Solo superadmins pueden cambiar roles' }); return; }
      fields.push(`role = $${idx++}`); values.push(role);
    }
    if (active !== undefined) {
      if (!isSuperadmin && isSelf) { res.status(403).json({ message: 'No puedes cambiar tu propio estado' }); return; }
      fields.push(`active = $${idx++}`); values.push(active);
    }
    if (password) {
      // Superadmin cambia la contrasena de cualquiera; el admin solo la de usuarios regulares.
      if (!isSuperadmin && targetRole !== 'user') {
        res.status(403).json({ message: 'Los administradores solo pueden cambiar contrasenas de usuarios' });
        return;
      }
      const hash = await bcrypt.hash(password, 12);
      fields.push(`password_hash = $${idx++}`);
      values.push(hash);
    }

    if (fields.length === 0) {
      res.status(400).json({ message: 'Nada que actualizar' });
      return;
    }

    fields.push(`updated_at = CURRENT_TIMESTAMP`);
    values.push(id);

    const result = await pool.query(
      `UPDATE users SET ${fields.join(', ')} WHERE id = $${idx}
       RETURNING id, username, full_name, dni, email, role, active`,
      values
    );

    res.json(result.rows[0]);
  } catch (err: any) {
    const conflict = conflictMessage(err);
    if (conflict) {
      res.status(409).json({ message: conflict });
      return;
    }
    console.error('Error al actualizar usuario:', err);
    res.status(500).json({ message: 'Error al actualizar usuario' });
  }
});

router.delete('/:id', requireRole('admin', 'superadmin'), async (req: AuthRequest, res: Response): Promise<void> => {
  const id = req.params.id as string;
  const isSuperadmin = req.user!.role === 'superadmin';

  if (parseInt(id) === req.user!.userId) {
    res.status(400).json({ message: 'No puedes eliminarte a ti mismo' });
    return;
  }

  try {
    const target = await pool.query('SELECT role FROM users WHERE id = $1', [id]);
    if (target.rows.length === 0) {
      res.status(404).json({ message: 'Usuario no encontrado' });
      return;
    }

    // Solo un superadmin puede eliminar administradores u otros superadmins
    if (!isSuperadmin && target.rows[0].role !== 'user') {
      res.status(403).json({ message: 'Solo un superadmin puede eliminar administradores' });
      return;
    }

    await pool.query('DELETE FROM users WHERE id = $1', [id]);
    res.json({ message: 'Usuario eliminado' });
  } catch (err) {
    console.error('Error al eliminar usuario:', err);
    res.status(500).json({ message: 'Error al eliminar usuario' });
  }
});

export default router;
